CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TYPE "StakeholderRole" AS ENUM ('CONSUMER','BUSINESS','LMO','GATC','STATE_ADMIN','CENTRAL_ADMIN');
CREATE TYPE "KycStatus" AS ENUM ('PENDING','VERIFIED','REJECTED');
CREATE TYPE "ApplicationStatus" AS ENUM ('DRAFT','SUBMITTED','UNDER_REVIEW','SCHEDULED','VERIFICATION_PASSED','VERIFICATION_FAILED','CERTIFICATE_ISSUED','REJECTED');
CREATE TYPE "VerificationResult" AS ENUM ('PASS','FAIL');
CREATE TYPE "CertificateStatus" AS ENUM ('ACTIVE','EXPIRED','REVOKED');
CREATE TABLE "stakeholders" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"role" "StakeholderRole" NOT NULL,"state_code" VARCHAR(5) NOT NULL,"name" TEXT NOT NULL,"email" TEXT,"phone" TEXT,"gstin" TEXT,"kyc_status" "KycStatus" NOT NULL DEFAULT 'PENDING',"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "stakeholders_pkey" PRIMARY KEY ("id"));
CREATE TABLE "instruments" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"owner_id" UUID NOT NULL,"category" TEXT NOT NULL,"model" TEXT,"serial_no" TEXT NOT NULL,"specs" JSONB,CONSTRAINT "instruments_pkey" PRIMARY KEY ("id"));
CREATE TABLE "applications" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"instrument_id" UUID NOT NULL,"applicant_id" UUID NOT NULL,"status" "ApplicationStatus" NOT NULL DEFAULT 'DRAFT',"fee_amount" DECIMAL(12,2),"assigned_officer_id" UUID,"scheduled_at" TIMESTAMPTZ,"submitted_at" TIMESTAMPTZ,"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "applications_pkey" PRIMARY KEY ("id"));
CREATE TABLE "verification_records" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"application_id" UUID NOT NULL,"officer_id" UUID NOT NULL,"observations" JSONB NOT NULL,"result" "VerificationResult" NOT NULL,"photos" TEXT[] NOT NULL,"verified_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "verification_records_pkey" PRIMARY KEY ("id"));
CREATE TABLE "certificates" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"verification_id" UUID NOT NULL,"cert_no" TEXT NOT NULL,"qr_hash" TEXT NOT NULL,"valid_from" TIMESTAMPTZ NOT NULL,"valid_until" TIMESTAMPTZ NOT NULL,"digital_signature" TEXT,"status" "CertificateStatus" NOT NULL DEFAULT 'ACTIVE',CONSTRAINT "certificates_pkey" PRIMARY KEY ("id"));
CREATE TABLE "payments" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"application_id" UUID NOT NULL,"provider_reference" TEXT,"amount" DECIMAL(12,2) NOT NULL,"status" TEXT NOT NULL DEFAULT 'PENDING',"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "payments_pkey" PRIMARY KEY ("id"));
CREATE TABLE "audit_logs" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"actor_id" UUID,"action" TEXT NOT NULL,"entity_type" TEXT NOT NULL,"entity_id" TEXT NOT NULL,"metadata" JSONB,"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "instruments_owner_id_serial_no_key" ON "instruments"("owner_id","serial_no");
CREATE UNIQUE INDEX "certificates_verification_id_key" ON "certificates"("verification_id");
CREATE UNIQUE INDEX "certificates_cert_no_key" ON "certificates"("cert_no");
CREATE INDEX "stakeholders_state_code_role_idx" ON "stakeholders"("state_code","role");
CREATE INDEX "applications_status_scheduled_at_idx" ON "applications"("status","scheduled_at");
CREATE INDEX "certificates_valid_until_status_idx" ON "certificates"("valid_until","status");
CREATE INDEX "audit_logs_entity_type_entity_id_created_at_idx" ON "audit_logs"("entity_type","entity_id","created_at");
ALTER TABLE "instruments" ADD CONSTRAINT "instruments_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "stakeholders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "applications" ADD CONSTRAINT "applications_instrument_id_fkey" FOREIGN KEY ("instrument_id") REFERENCES "instruments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "applications" ADD CONSTRAINT "applications_applicant_id_fkey" FOREIGN KEY ("applicant_id") REFERENCES "stakeholders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "verification_records" ADD CONSTRAINT "verification_records_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_verification_id_fkey" FOREIGN KEY ("verification_id") REFERENCES "verification_records"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "payments" ADD CONSTRAINT "payments_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
