'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Icon } from '../../components/icons';
import { PageHeader, Status } from '../../components/ui';

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000/api';
type PaymentRow = { id: string; applicationId: string; applicant: string; amount: number; date: string; status: string; tone: string; reference: string };
const fallback: PaymentRow[] = [
  { id: 'PAY-2026-00981', applicationId: 'APP-2026-01482', applicant: 'Shree Om Retail Pvt Ltd', amount: 500, date: '18 Sep 2026', status: 'Success', tone: 'green', reference: 'UTR 88A1' },
  { id: 'PAY-2026-00977', applicationId: 'APP-2026-01479', applicant: 'Arjun Fuel Station', amount: 1250, date: '17 Sep 2026', status: 'Success', tone: 'green', reference: 'UTR 88A2' },
  { id: 'PAY-2026-00964', applicationId: 'APP-2026-01468', applicant: 'Neelam Traders', amount: 500, date: '15 Sep 2026', status: 'Refund pending', tone: 'amber', reference: 'UTR 88A3' },
];
const money = (amount: number) => `₹ ${amount.toLocaleString('en-IN')}`;
function mapPayment(payment: any, application: any): PaymentRow { const status = payment.status === 'SUCCESS' ? 'Success' : payment.status === 'REFUND_PENDING' ? 'Refund pending' : payment.status === 'FAILED' ? 'Refund pending' : 'Pending'; return { id: payment.id, applicationId: application.id, applicant: application.applicant?.name || 'Applicant', amount: Number(payment.amount), date: new Date(payment.createdAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), status, tone: status === 'Success' ? 'green' : status === 'Refund pending' ? 'amber' : 'blue', reference: payment.providerReference || 'Gateway pending' }; }

export default function Payments() {
  const [payments, setPayments] = useState<PaymentRow[]>([]);
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('All statuses');
  useEffect(() => { const token = sessionStorage.getItem('metrology_access_token'); if (!token) { setPayments(fallback); return; } fetch(`${API}/applications`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.ok ? response.json() : Promise.reject()).then((apps) => setPayments(apps.flatMap((application: any) => (application.payments || []).map((payment: any) => mapPayment(payment, application))))).catch(() => setPayments(fallback)); }, []);
  const visible = useMemo(() => payments.filter((payment) => `${payment.id} ${payment.applicationId} ${payment.applicant}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All statuses' || payment.status === status)), [payments, query, status]);
  const successful = payments.filter((payment) => payment.status === 'Success');
  const collected = successful.reduce((total, payment) => total + payment.amount, 0);
  const exportPayments = () => { const header = ['Payment', 'Application', 'Applicant', 'Amount', 'Date', 'Status', 'Reference']; const rows = visible.map((payment) => [payment.id, payment.applicationId, payment.applicant, payment.amount, payment.date, payment.status, payment.reference]); const csv = [header, ...rows].map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: 'text/csv;charset=utf-8;' })); const link = document.createElement('a'); link.href = url; link.download = `payments-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); };
  return <><PageHeader eyebrow="FINANCE / PAYMENTS" title="Payments" description="Track application fees, receipts, and reconciliation status."/><div className="kpi-grid compact"><div className="mini-kpi"><span>Collected in view</span><b>{money(collected)}</b><i className="green-text">{successful.length} successful transactions</i></div><div className="mini-kpi"><span>Successful transactions</span><b>{successful.length}</b><i className="green-text">Receipts available</i></div><div className="mini-kpi"><span>Needs reconciliation</span><b>{payments.filter((payment) => payment.status === 'Refund pending').length}</b><i className="amber-text">Review pending refunds</i></div></div><div className="filter-row payments-toolbar"><div className="search-box"><Icon name="search" size={14}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search payment or application" aria-label="Search payments"/></div><select className="filter-button" value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter payments by status"><option>All statuses</option><option>Success</option><option>Refund pending</option><option>Pending</option></select><button type="button" className="button export-button" onClick={exportPayments}><Icon name="download" size={14}/> Export CSV</button></div><div className="section-card flush"><div className="table-toolbar"><span><b>{visible.length}</b> payments</span><span className="muted">{visible.length === payments.length ? 'All records' : 'Filtered results'}</span></div><div className="table-wrap"><table><thead><tr><th>Payment</th><th>Application</th><th>Applicant</th><th>Amount</th><th>Date</th><th>Status</th><th></th></tr></thead><tbody>{visible.map((payment) => <tr key={payment.id}><td><Link className="table-link" href={`/dashboard/payments/${payment.id}`}>{payment.id}</Link><small>{payment.reference}</small></td><td><Link className="table-link" href={`/dashboard/applications/${payment.applicationId}`}>{payment.applicationId}</Link></td><td>{payment.applicant}</td><td><b>{money(payment.amount)}</b></td><td>{payment.date}</td><td><Status tone={payment.tone as any}>{payment.status}</Status></td><td><Link className="row-more" href={`/dashboard/payments/${payment.id}`} aria-label={`Open ${payment.id}`}>↗</Link></td></tr>)}</tbody></table>{!visible.length&&<div className="verification-empty"><div className="verification-empty-icon"><Icon name="search" size={22}/></div><h3>No payments found</h3><p>Try a different payment search or status filter.</p></div>}</div></div></>;
}
