'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { applications } from '../../../data';
import { PageHeader, Section, Status } from '../../../components/ui';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:3000/api';
const labels:any={WEIGHING_SCALE:'Electronic weighing scale',FUEL_DISPENSER:'Fuel dispenser',WEIGHBRIDGE:'Weighbridge',PLATFORM_SCALE:'Platform scale'};
const statuses:any={UNDER_REVIEW:'Under review',SCHEDULED:'Scheduled',CERTIFICATE_ISSUED:'Certificate issued',VERIFICATION_FAILED:'Verification failed',SUBMITTED:'Submitted',REJECTED:'Rejected'};
export default function ApplicationDetail({params}:{params:{id:string}}){
 const [id,setId]=useState('');const [a,setA]=useState<any>(null);const [canManage,setCanManage]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{const {id}=params;setId(id);const token=sessionStorage.getItem('metrology_access_token');if(!token){const demo=applications.find(x=>x.id===id)||applications[0];setA(demo);return;}Promise.all([fetch(`${API}/applications/${id}`,{headers:{Authorization:`Bearer ${token}`}}),fetch(`${API}/stakeholders/me`,{headers:{Authorization:`Bearer ${token}`}})]).then(async([appRes,profileRes])=>{if(!appRes.ok)throw new Error(appRes.status===403?'You do not have access to this application.':'Application not found');const app=await appRes.json();const profile=profileRes.ok?await profileRes.json():null;setCanManage(['STATE_ADMIN','CENTRAL_ADMIN'].includes(profile?.role));setA({id:app.id,owner:app.applicant?.name||'—',instrument:labels[app.instrument?.category]||app.instrument?.category||'Instrument',serial:app.instrument?.serialNo||'—',district:app.applicant?.districtCode||app.applicant?.stateCode||'—',date:new Date(app.submittedAt||app.createdAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),status:statuses[app.status]||app.status,tone:app.status==='CERTIFICATE_ISSUED'?'green':app.status==='VERIFICATION_FAILED'||app.status==='REJECTED'?'red':app.status==='SCHEDULED'?'amber':'blue',fee:`₹ ${Number(app.feeAmount||0).toLocaleString('en-IN')}`});}).catch(e=>setError(e.message));},[params.id]);
 if(error)return <><div className="back-link"><Link href="/dashboard/applications">← Applications</Link></div><div className="empty-state">{error}</div></>;
 if(!a)return <div className="empty-state">Loading application…</div>;
 return <><div className="back-link"><Link href="/dashboard/applications">← Applications</Link></div><PageHeader eyebrow="APPLICATION DETAIL" title={a.id} description={`${a.owner} · submitted ${a.date}`} {...(canManage?{action:'Assign visit',actionHref:'/dashboard/schedule'}:{})}/><div className="detail-grid"><Section title="Application timeline"><div className="timeline"><div className="timeline-item done"><i>✓</i><div><b>Application submitted</b><span>{a.date}</span></div></div><div className="timeline-item done"><i>✓</i><div><b>Documents reviewed</b><span>Application documents received</span></div></div><div className="timeline-item current"><i>3</i><div><b>Verification visit</b><span>{a.status==='Scheduled'?'Appointment allocated':'Waiting for appointment allocation'}</span></div></div><div className="timeline-item"><i>4</i><div><b>Certificate issued</b><span>Pending verification outcome</span></div></div></div></Section><Section title="Application summary"><div className="detail-list"><div><span>Applicant</span><b>{a.owner}</b></div><div><span>Instrument</span><b>{a.instrument}</b></div><div><span>Serial number</span><b>{a.serial}</b></div><div><span>District</span><b>{a.district}</b></div><div><span>Fee status</span><Status tone="green">Paid · {a.fee}</Status></div><div><span>Current status</span><Status tone={a.tone as any}>{a.status}</Status></div></div></Section></div></>;
}
