'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Icon } from '../../../components/icons';

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000/api';
const demo = { 'PAY-2026-00981': { id: 'PAY-2026-00981', applicationId: 'APP-2026-01482', applicant: 'Shree Om Retail Pvt Ltd', amount: 500, status: 'Success', date: '18 Sep 2026', reference: 'UTR 88A1', receipt: 'RCT-2026-00981' }, 'PAY-2026-00964': { id: 'PAY-2026-00964', applicationId: 'APP-2026-01468', applicant: 'Neelam Traders', amount: 500, status: 'Refund pending', date: '15 Sep 2026', reference: 'UTR 88A3', receipt: '—' } } as Record<string, any>;

export default function PaymentDetail({ params }: { params: { id: string } }) {
  const [payment, setPayment] = useState<any>(demo[params.id] || null);
  useEffect(() => { const token = sessionStorage.getItem('metrology_access_token'); if (!token || params.id.startsWith('PAY-')) return; fetch(`${API}/payments/${params.id}/receipt`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.ok ? response.json() : null).then((data) => data && setPayment({ id: data.id, applicationId: data.applicationId, applicant: data.application.applicant.name, amount: Number(data.amount), status: data.status === 'SUCCESS' ? 'Success' : data.status === 'REFUND_PENDING' || data.status === 'FAILED' ? 'Refund pending' : 'Pending', date: new Date(data.createdAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), reference: data.providerReference || 'Gateway pending', receipt: data.receiptNo || '—' })).catch(() => undefined); }, [params.id]);
  if (!payment) return <div className="section-card">Payment record not found.</div>;
  const success = payment.status === 'Success';
  return <><div className="back-link"><Link href="/dashboard/payments">← Payments</Link></div><div className="page-header"><div><span className="eyebrow">FINANCE / PAYMENT DETAIL</span><h1>{payment.id}</h1><p>{payment.applicant} · {payment.applicationId}</p></div><span className={success ? 'status green' : 'status amber'}>{success ? 'Success' : 'Refund pending'}</span></div><div className="payment-detail-layout"><div className="payment-receipt-card"><div className={`payment-hero ${success ? 'payment-success' : 'payment-refund'}`}><div className="payment-hero-icon"><Icon name={success ? 'checkCircle' : 'clock'} size={25}/></div><div><span>{success ? 'Payment received' : 'Refund is being processed'}</span><b>{success ? 'Transaction successful' : 'Refund pending review'}</b><small>{success ? 'The application fee has been reconciled and the receipt is ready.' : 'The original payment is recorded. The finance team is tracking the refund.'}</small></div></div><div className="payment-fields"><div><span>Amount</span><b>₹ {payment.amount.toLocaleString('en-IN')}</b></div><div><span>Payment date</span><b>{payment.date}</b></div><div><span>Application</span><Link href={`/dashboard/applications/${payment.applicationId}`}>{payment.applicationId}</Link></div><div><span>Reference</span><b>{payment.reference}</b></div><div><span>Receipt number</span><b>{payment.receipt}</b></div><div><span>Payment method</span><b>Mock gateway · UPI</b></div></div>{success ? <div className="receipt-ready"><Icon name="document" size={18}/><div><b>Receipt ready to view</b><small>Download or present this receipt during evaluation.</small></div><button type="button" className="button" onClick={() => window.print()}>Print receipt</button></div> : <div className="refund-timeline"><b>Refund tracking</b><div className="refund-step done"><i>✓</i><span><strong>Payment recorded</strong><small>{payment.date}</small></span></div><div className="refund-step current"><i>2</i><span><strong>Refund pending finance review</strong><small>Expected resolution within 5–7 working days</small></span></div><div className="refund-step"><i>3</i><span><strong>Refund credited</strong><small>Confirmation will be added here</small></span></div></div>}</div><div className="payment-side"><div className="section-card"><span className="eyebrow">APPLICATION</span><h2>Payment context</h2><p>This payment is linked to the instrument verification application and is visible only to authorized users in the application scope.</p><Link className="button full-button" href={`/dashboard/applications/${payment.applicationId}`}>View application →</Link></div><div className="section-card payment-security"><Icon name="lock" size={18}/><div><b>Secure record</b><span>Audit trail and gateway references are retained by the department.</span></div></div></div></div></>;
}
