'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Icon } from '../../components/icons';
import { PageHeader, Status } from '../../components/ui';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:3000/api';
const statusOptions=['All statuses','Under review','Scheduled','Certificate issued','Verification failed','Submitted','Rejected'];
const previewApplications=[{id:'APP-2026-01482',owner:'Shree Om Retail Pvt Ltd',instrument:'Electronic weighing scale',serial:'SCALE-88412',district:'South Delhi',date:'18 Sep 2026',status:'Under review',tone:'blue',fee:'₹ 500'},{id:'APP-2026-01479',owner:'Arjun Fuel Station',instrument:'Fuel dispenser',serial:'FD-22091',district:'Gurugram',date:'17 Sep 2026',status:'Scheduled',tone:'amber',fee:'₹ 1,250'},{id:'APP-2026-01471',owner:'Metro Weighbridge',instrument:'Weighbridge',serial:'WB-00981',district:'East Delhi',date:'16 Sep 2026',status:'Certificate issued',tone:'green',fee:'₹ 2,400'}];
type ApplicationRow=typeof previewApplications[number];
const categoryLabel=(value:string)=>({WEIGHING_SCALE:'Electronic weighing scale',FUEL_DISPENSER:'Fuel dispenser',WEIGHBRIDGE:'Weighbridge',PLATFORM_SCALE:'Platform scale'} as Record<string,string>)[value]||value.replaceAll('_',' ');
function mapApplication(app:any):ApplicationRow { const statusMap:any={UNDER_REVIEW:'Under review',SCHEDULED:'Scheduled',CERTIFICATE_ISSUED:'Certificate issued',VERIFICATION_FAILED:'Verification failed',SUBMITTED:'Submitted',REJECTED:'Rejected'}; const status=statusMap[app.status]||app.status; const tone=status==='Certificate issued'?'green':status==='Verification failed'||status==='Rejected'?'red':status==='Scheduled'?'amber':'blue'; return {id:app.id,owner:app.applicant?.name||'—',instrument:categoryLabel(app.instrument?.category||'Instrument'),serial:app.instrument?.serialNo||'—',district:app.applicant?.districtCode||app.applicant?.stateCode||'—',date:new Date(app.submittedAt||app.createdAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),status,tone,fee:`₹ ${Number(app.feeAmount||0).toLocaleString('en-IN')}`}; }
export default function Applications(){
 const [query,setQuery]=useState('');const [status,setStatus]=useState('All statuses');const [month,setMonth]=useState('All months');const [records,setRecords]=useState<ApplicationRow[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{const token=sessionStorage.getItem('metrology_access_token');if(!token){setRecords(previewApplications);setLoading(false);return;}fetch(`${API}/applications`,{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{if(!r.ok)throw new Error('Unable to load applications');return r.json();}).then(data=>setRecords(data.map(mapApplication))).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 const monthOptions=useMemo(()=>['All months',...Array.from(new Set(records.map(a=>a.date.replace(/^\d+ /,''))))],[records]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return records.filter(a=>(!q||[a.id,a.owner,a.instrument,a.serial,a.district].some(v=>v.toLowerCase().includes(q)))&&(status==='All statuses'||a.status===status)&&(month==='All months'||a.date.endsWith(month)));},[records,query,status,month]);
 function resetFilters(){setQuery('');setStatus('All statuses');setMonth('All months');}
 function exportApplications(){const header=['Application ID','Applicant','Instrument','Serial number','District','Submitted','Status','Fee'];const rows=filtered.map(a=>[a.id,a.owner,a.instrument,a.serial,a.district,a.date,a.status,a.fee]);const csv=[header,...rows].map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([`\uFEFF${csv}`],{type:'text/csv;charset=utf-8;'}));const link=document.createElement('a');link.href=url;link.download=`applications-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);}
 return <><PageHeader eyebrow="WORKSPACE / APPLICATIONS" title="Applications" description="Track verification requests within your access scope." action="New application" actionHref="/dashboard/applications/new"/><div className="filter-row applications-toolbar"><div className="search-box"><Icon name="search" size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search application, applicant or serial number" aria-label="Search applications"/></div><select className="filter-button" value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter by status">{statusOptions.map(o=><option key={o}>{o}</option>)}</select><select className="filter-button" value={month} onChange={e=>setMonth(e.target.value)} aria-label="Filter by submission month">{monthOptions.map(o=><option key={o}>{o}</option>)}</select><button type="button" className="ghost-button reset-button" onClick={resetFilters}>Reset filters</button><button type="button" className="button export-button" onClick={exportApplications}><Icon name="download" size={14}/> Export CSV</button></div><div className="section-card flush"><div className="table-toolbar"><span><b>{filtered.length}</b> applications</span><span className="muted">{loading?'Loading…':error||(filtered.length===records.length?'All records in your scope':'Filtered results')}</span></div><div className="table-wrap"><table><thead><tr><th>Application</th><th>Applicant</th><th>Instrument</th><th>District</th><th>Submitted</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(a=><tr key={a.id}><td><Link className="table-link" href={`/dashboard/applications/${a.id}`}>{a.id}</Link><small>{a.fee} fee</small></td><td>{a.owner}</td><td><b>{a.instrument}</b><small>{a.serial}</small></td><td>{a.district}</td><td>{a.date}</td><td><Status tone={a.tone as any}>{a.status}</Status></td><td><Link className="row-more" href={`/dashboard/applications/${a.id}`}>→</Link></td></tr>)}</tbody></table>{!loading&&!filtered.length&&<div className="empty-state">{error||'No applications match the selected filters.'}</div>}</div><div className="pagination"><span>Showing {filtered.length?`1–${filtered.length}`:'0'} of {filtered.length}</span><span><button type="button" className="page-btn selected">1</button></span></div></div></>;
}
