'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Icon } from '../../components/icons';
import { PageHeader, Status } from '../../components/ui';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:3000/api';
const fallback=[['APP-2026-01482','SCALE-88412','Electronic weighing scale','Shree Om Retail Pvt Ltd','South Delhi','Active','green'],['APP-2026-01479','FD-22091','Fuel dispenser','Arjun Fuel Station','Gurugram','Verification due','amber'],['APP-2026-01471','WB-00981','Weighbridge','Metro Weighbridge','East Delhi','Active','green'],['APP-2026-01468','PS-11903','Platform scale','Neelam Traders','Noida','Not valid','red'],['APP-2026-01451','WB-00444','Weighbridge','Sagar Logistics','Faridabad','Active','green']];
const categoryLabel=(value:string)=>({WEIGHING_SCALE:'Electronic weighing scale',FUEL_DISPENSER:'Fuel dispenser',WEIGHBRIDGE:'Weighbridge',PLATFORM_SCALE:'Platform scale'} as Record<string,string>)[value]||value.replaceAll('_',' ');
type RecordItem={id:string;serial:string;type:string;owner:string;district:string;status:string;tone:string;verified:string};
function mapApi(app:any):RecordItem{const status=app.status==='CERTIFICATE_ISSUED'?'Active':app.status==='VERIFICATION_FAILED'||app.status==='REJECTED'?'Not valid':app.status==='SCHEDULED'?'Verification due':'Under review';const tone=status==='Active'?'green':status==='Not valid'?'red':status==='Verification due'?'amber':'blue';const verified=app.verifications?.at(-1)?.verifiedAt?new Date(app.verifications.at(-1).verifiedAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'Not verified yet';return {id:app.id,serial:app.instrument.serialNo,type:categoryLabel(app.instrument.category),owner:app.applicant.name,district:app.applicant.districtCode||app.applicant.stateCode||'—',status,tone,verified};}
export default function Instruments(){const [items,setItems]=useState<RecordItem[]>([]);const [query,setQuery]=useState('');const [category,setCategory]=useState('');const [status,setStatus]=useState('');
useEffect(()=>{const token=sessionStorage.getItem('metrology_access_token');if(!token){setItems(fallback.map(([id,serial,type,owner,district,status,tone])=>({id,serial,type,owner,district,status,tone,verified:'16 Sep 2026'})));return;}fetch(`${API}/applications`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.ok?r.json():Promise.reject()).then(data=>setItems(data.map(mapApi))).catch(()=>setItems([]));},[]);
const visible=useMemo(()=>items.filter(i=>`${i.serial} ${i.type} ${i.owner} ${i.district}`.toLowerCase().includes(query.toLowerCase())&&(!category||i.type===category)&&(!status||i.status===status)),[items,query,category,status]);const categories=Array.from(new Set(items.map(i=>i.type)));return <><PageHeader eyebrow="RECORDS / INSTRUMENTS" title="Instrument registry" description="A complete, searchable record of instruments under verification." action="Add instrument" actionHref="/dashboard/applications/new"/><div className="filter-row"><div className="search-box"><Icon name="search" size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search serial number, owner or category"/></div><select className="filter-button" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select className="filter-button" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['Active','Verification due','Under review','Not valid'].map(s=><option key={s}>{s}</option>)}</select></div><div className="instrument-grid">{visible.map(i=><Link href={`/dashboard/applications/${i.id}`} className="instrument-card" key={i.id}><div className="instrument-icon"><Icon name="gauge" size={20}/></div><div className="instrument-card-top"><Status tone={i.tone as any}>{i.status}</Status><span>•••</span></div><h3>{i.type}</h3><p>{i.owner}</p><div className="instrument-meta"><span><small>Serial number</small><b>{i.serial}</b></span><span><small>Location</small><b>{i.district}</b></span></div><div className="instrument-footer">Last verified {i.verified}<span>→</span></div></Link>)}</div>{!visible.length&&<div className="empty-state">No instruments match the selected filters.</div>}</>}
