'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { PageHeader } from '../../components/ui';
import { getToken } from '../../auth';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:3000/api';
type AiOutput={id:string;kind:string;documentType:string|null;inputObjectKey:string;result:Record<string,unknown>;confidence:string;lowConfidence:boolean;status:string;createdAt:string};
const headers=()=>({'Content-Type':'application/json',...(getToken()?{Authorization:`Bearer ${getToken()}`}:{})});
export default function AiReview(){const [outputs,setOutputs]=useState<AiOutput[]>([]);const [loading,setLoading]=useState(true);const load=()=>fetch(`${API}/ai/outputs`,{headers:headers()}).then(r=>r.ok?r.json():[]).then(setOutputs).finally(()=>setLoading(false));useEffect(()=>{load();},[]);const pending=outputs.filter(o=>o.status==='PENDING_REVIEW');const reviewed=outputs.filter(o=>o.status!=='PENDING_REVIEW');return <><PageHeader eyebrow="INTELLIGENCE / AI ASSIST" title="AI review queue" description="Review deterministic mock intelligence results before they are applied to a record."/><div className="content-grid"><Link className="section-card" href="/dashboard/ai-review/ocr"><span className="eyebrow">DOCUMENT INTELLIGENCE</span><h2>Extract fields</h2><p className="side-copy">Run OCR on the demo Business PAN card and review the extracted identity fields.</p><span className="button">Open OCR page →</span></Link><Link className="section-card" href="/dashboard/ai-review/recognition"><span className="eyebrow">INSTRUMENT INTELLIGENCE</span><h2>Recognize category</h2><p className="side-copy">Run fixed mock recognition on an instrument photo and review the predicted category.</p><span className="button">Open recognition page →</span></Link></div><div className="section-card" style={{marginTop:22}}><div className="section-title"><h2>Pending review ({pending.length})</h2></div>{loading&&<p className="muted">Loading…</p>}{!loading&&!pending.length&&<p className="muted">Nothing waiting on human review.</p>}{pending.map(o=><div className="ai-output-card" key={o.id}><div className="ai-output-head"><b>{o.kind}{o.documentType?` · ${o.documentType}`:''}</b><span className="ai-confidence-badge ok">{(Number(o.confidence)*100).toFixed(0)}% confidence</span></div><div className="muted" style={{fontSize:10}}>{o.inputObjectKey}</div></div>)}</div><div className="section-card" style={{marginTop:22}}><div className="section-title"><h2>AI output audit history</h2></div>{!reviewed.length&&<p className="muted">No reviewed outputs yet.</p>}{reviewed.map(o=><div className="ai-output-card" key={o.id}><div className="ai-output-head"><b>{o.kind}{o.documentType?` · ${o.documentType}`:''}</b><span className="ai-confidence-badge ok">{o.status}</span></div><div className="muted" style={{fontSize:10}}>{o.inputObjectKey} · {new Date(o.createdAt).toLocaleString()}</div></div>)}</div></>}
